src/components/can_cooperation/include/can_cooperation/commands/base_command_notification.h, src/components/can_cooperation/src/can_module.cc, src/components/can_cooperation/src/command/base_command_notification.cc, src/components/can_cooperation/src/command/on_control_changed_notification.cc, src/components/can_cooperation/test/src/can_module_test.cc
=> REVSDL-995: One instance object of notification

src/components/can_cooperation/reverse_sdl_pt.json
=> Hotfix: Temp solution for checking grant access

src/components/can_cooperation/reverse_sdl_pt.json, src/components/policy/src/policy/include/policy/access_remote_impl.h, src/components/policy/src/policy/include/policy/policy_types.h, src/components/policy/src/policy/src/access_remote_impl.cc, src/components/policy/src/policy/src/policy_helper.cc, src/components/policy/src/policy/src/sql_pt_representation.cc
Fixed REVSDL-1062 and REVSDL-1054
=> REVSDL-1062: add pre_consent_passengersRC section

src/components/application_manager/src/core_service.cc, src/components/can_cooperation/reverse_sdl_pt.json, src/components/policy/src/policy/src/access_remote_impl.cc, src/components/policy/src/policy/src/sql_pt_queries.cc, src/components/policy/src/policy/src/sql_pt_representation.cc
=> REVSDL-1339: fix keeping remote rpc in database

src/components/application_manager/src/policies/policy_handler.cc, src/components/can_cooperation/reverse_sdl_pt.json, src/components/policy/src/policy/src/cache_manager.cc
fixed policy snapshot and exchange process
=> REVSDL-1060: fixed policy snapshot and exchange process

src/components/can_cooperation/src/module_helper.cc
SDL activates mobile application from non_primary device.
=> REVSDL-1374: fix activation of app from non-primary device.

src/components/rpc_base/include/rpc_base/rpc_base.h, src/components/rpc_base/include/rpc_base/rpc_base_json_inl.h
=> Fix Integer template

src/components/ivdcm_module/interface/rpc.proto
Define GPB API between SDL and IVDCM
=> CM-87: Define GPB proto file

cmake/Modules/FindPCAP.cmake, src/components/ivdcm_module/CMakeLists.txt, src/components/ivdcm_module/include/ivdcm_module/pcap_wrapper.h, src/components/ivdcm_module/readme.md, src/components/ivdcm_module/src/pcap_wrapper.cc
=> Integration of pcap

src/components/ivdcm_module/CMakeLists.txt, src/components/ivdcm_module/include/ivdcm_module/gpb_data_sender_receiver.h, src/components/ivdcm_module/include/ivdcm_module/ivdcm.h, src/components/ivdcm_module/include/ivdcm_module/ivdcm_proxy.h, src/components/ivdcm_module/include/ivdcm_module/ivdcm_proxy_listener.h, src/components/ivdcm_module/src/gpb_data_sender_receiver.cc, src/components/ivdcm_module/src/ivdcm.cc, src/components/ivdcm_module/src/ivdcm_proxy.cc, src/components/ivdcm_module/utils/scope_guard.h, src/components/ivdcm_module/utils/types.h
- IvdcmProxy
- GpbDataSenderReceiver
=> Add IvdcmProxy and stubs for GPB comunication

src/components/vr_cooperation/CMakeLists.txt, src/components/vr_cooperation/include/vr_cooperation/gpb_data_sender_receiver.h, src/components/vr_cooperation/include/vr_cooperation/vr_proxy.h, src/components/vr_cooperation/src/gpb_data_sender_receiver.cc, src/components/vr_cooperation/src/vr_proxy.cc
@bonewell 
@KKarlash 
@VladSemenyuk 
@DKlimenko 
@thinhts 
please review
=> REVSDL-2377 Skeleton for GPB handling

src/components/vr_cooperation/CMakeLists.txt, src/components/vr_cooperation/include/vr_cooperation/commands/activate_service_request.h, src/components/vr_cooperation/include/vr_cooperation/commands/active_service_request.h, src/components/vr_cooperation/include/vr_cooperation/commands/base_command_request.h, src/components/vr_cooperation/include/vr_cooperation/commands/register_service_request.h, src/components/vr_cooperation/include/vr_cooperation/commands/unregister_service_request.h, src/components/vr_cooperation/include/vr_cooperation/mobile_command_factory.h, src/components/vr_cooperation/include/vr_cooperation/vr_module.h, src/components/vr_cooperation/src/activate_service_request.cc, src/components/vr_cooperation/src/active_service_request.cc, src/components/vr_cooperation/src/base_command_request.cc, src/components/vr_cooperation/src/mobile_command_factory.cc, src/components/vr_cooperation/src/register_service_request.cc, src/components/vr_cooperation/src/unregister_service_request.cc
add mobile command factory for VR Plugin
fix load plugin error
@giangtqh 
@KKarlash 
@bonewell 
@DKlimenko 
@VladSemenyuk
=> REVSDL-2379 Mobile command factory for VR Plugin

src/components/vr_cooperation/CMakeLists.txt, src/components/vr_cooperation/include/vr_cooperation/commands/activate_service_request.h, src/components/vr_cooperation/include/vr_cooperation/commands/base_command_request.h, src/components/vr_cooperation/include/vr_cooperation/commands/register_service_request.h, src/components/vr_cooperation/include/vr_cooperation/commands/unregister_service_request.h, src/components/vr_cooperation/include/vr_cooperation/message_helper.h, src/components/vr_cooperation/include/vr_cooperation/mobile_command_factory.h, src/components/vr_cooperation/include/vr_cooperation/vr_module.h, src/components/vr_cooperation/include/vr_cooperation/vr_module_constants.h, src/components/vr_cooperation/src/activate_service_request.cc, src/components/vr_cooperation/src/base_command_request.cc, src/components/vr_cooperation/src/message_helper.cc, src/components/vr_cooperation/src/mobile_command_factory.cc, src/components/vr_cooperation/src/register_service_request.cc, src/components/vr_cooperation/src/unregister_service_request.cc, src/components/vr_cooperation/src/vr_module.cc
@bonewell 
@DKlimenko 
@VladSemenyuk 
@giangtqh 
@thinhts
=> REVSDL-2388 ActivateServiceRequest implementation

src/components/vr_cooperation/CMakeLists.txt, src/components/vr_cooperation/include/vr_cooperation/commands/on_service_deactivated_notification.h, src/components/vr_cooperation/src/on_service_deactivated_notification.cc, src/components/vr_cooperation/src/vr_module.cc
@bonewell 
@KKarlash 
@VladSemenyuk 
@DKlimenko 
@thinhts 
please review
=> REVSDL-2389 OnServiceDeactivated notification implementation

src/components/functional_module/include/functional_module/function_ids.h, src/components/vr_cooperation/include/vr_cooperation/mobile_command_factory.h, src/components/vr_cooperation/include/vr_cooperation/vr_module.h, src/components/vr_cooperation/src/mobile_command_factory.cc, src/components/vr_cooperation/src/vr_module.cc
@KKarlash 
@bonewell 
@VladSemenyuk 
@DKlimenko 
@thinhts 
please review
=> REVSDL-2458 Update VRModule for GPB functionality

src/components/vr_module/include/vr_module/event_engine/event.h, src/components/vr_module/include/vr_module/event_engine/event_dispatcher.h, src/components/vr_module/include/vr_module/vr_module_event.h, src/components/vr_module/src/vr_module_event.cc
- Remove dependce on xml api of SDL
=> Improve event engine

src/components/vr_cooperation/CMakeLists.txt, src/components/vr_cooperation/include/vr_cooperation/commands/request_from_hmi.h, src/components/vr_cooperation/include/vr_cooperation/event_engine/event.h, src/components/vr_cooperation/include/vr_cooperation/event_engine/event_dispatcher.h, src/components/vr_cooperation/include/vr_cooperation/hmi_command_factory.h, src/components/vr_cooperation/include/vr_cooperation/vr_module_event_gpb.h, src/components/vr_cooperation/src/hmi_command_factory.cc, src/components/vr_cooperation/src/request_from_hmi.cc, src/components/vr_cooperation/src/vr_module.cc, src/components/vr_cooperation/src/vr_module_event_gpb.cc
@bonewell 
@KKarlash 
@VladSemenyuk 
@DKlimenko 
@thinhts 
please review
=> REVSDL-2470 HMICommandFactory to handle GPB message from HMI

src/components/vr_cooperation/include/vr_cooperation/commands/base_command_request.h, src/components/vr_cooperation/include/vr_cooperation/commands/register_service_request.h, src/components/vr_cooperation/include/vr_cooperation/vr_module.h, src/components/vr_cooperation/src/base_command_request.cc, src/components/vr_cooperation/src/register_service_request.cc, src/components/vr_cooperation/src/vr_module.cc
@bonewell 
@DKlimenko 
@KKarlash 
@VladSemenyuk 
@giangtqh
=> REVSDL-2459 RegisterService request GPB implementation

src/components/vr_cooperation/include/vr_cooperation/commands/activate_service_request.h, src/components/vr_cooperation/include/vr_cooperation/commands/base_command_request.h, src/components/vr_cooperation/include/vr_cooperation/vr_module.h, src/components/vr_cooperation/src/activate_service_request.cc, src/components/vr_cooperation/src/base_command_request.cc, src/components/vr_cooperation/src/register_service_request.cc, src/components/vr_cooperation/src/vr_module.cc
@bonewell 
@DKlimenko 
@VladSemenyuk 
@thinhts  
@giangtqh
=> Updated implementation of ActivateService for GPB

src/components/vr_cooperation/CMakeLists.txt, src/components/vr_cooperation/include/vr_cooperation/commands/request_from_hmi.h, src/components/vr_cooperation/include/vr_cooperation/commands/support_service_request.h, src/components/vr_cooperation/include/vr_cooperation/vr_module.h, src/components/vr_cooperation/interface/hmi.proto, src/components/vr_cooperation/src/support_service_request.cc, src/components/vr_cooperation/src/vr_module.cc
@bonewell 
@DKlimenko 
@VladSemenyuk 
@thinhts
@giangtqh
=> Support service implementation

src/components/vr_module/include/vr_module/commands/activate_service.h, src/components/vr_module/include/vr_module/commands/async_command.h, src/components/vr_module/include/vr_module/commands/command.h, src/components/vr_module/include/vr_module/commands/factory.h, src/components/vr_module/include/vr_module/commands/factory_interface.h, src/components/vr_module/include/vr_module/commands/on_default_service_chosen.h, src/components/vr_module/include/vr_module/commands/on_register_service.h, src/components/vr_module/include/vr_module/commands/on_service_deactivated.h, src/components/vr_module/include/vr_module/commands/process_data.h, src/components/vr_module/include/vr_module/commands/support_service.h, src/components/vr_module/include/vr_module/commands/timed_command.h, src/components/vr_module/include/vr_module/request_controller.h, src/components/vr_module/include/vr_module/vr_module.h, src/components/vr_module/src/commands/factory.cc, src/components/vr_module/src/commands/on_default_service_chosen.cc, src/components/vr_module/src/commands/on_service_deactivated.cc, src/components/vr_module/src/request_controller.cc, src/components/vr_module/src/vr_module.cc
- Add TimedCommand to interrupt running of command
- Add AsyncCommand to run command asynchronously
=> Improve commands system:

src/components/vr_cooperation/CMakeLists.txt, src/components/vr_cooperation/include/vr_cooperation/commands/base_command_notification.h, src/components/vr_cooperation/include/vr_cooperation/commands/on_service_deactivated_notification.h, src/components/vr_cooperation/include/vr_cooperation/vr_module_constants.h, src/components/vr_cooperation/src/base_command_notification.cc, src/components/vr_cooperation/src/hmi_command_factory.cc, src/components/vr_cooperation/src/on_service_deactivated_notification.cc
@bonewell 
@KKarlash 
@thinhts 
@DKlimenko 
@VladSemenyuk 
please review
=> REVSDL-2456 OnServiceDeactivate notification GPB

src/components/vr_cooperation/CMakeLists.txt, src/components/vr_cooperation/include/vr_cooperation/commands/process_data_request.h, src/components/vr_cooperation/include/vr_cooperation/vr_module_constants.h, src/components/vr_cooperation/src/process_data_request.cc
@bonewell 
@DKlimenko 
@VladSemenyuk 
@thinhts 
@giangtqh
=> Process data implementation

src/components/vr_cooperation/CMakeLists.txt, src/components/vr_cooperation/include/vr_cooperation/commands/gpb_notification.h, src/components/vr_cooperation/include/vr_cooperation/commands/on_register_service_notification.h, src/components/vr_cooperation/src/command/gpb_notification.cc, src/components/vr_cooperation/src/command/on_register_service_notification.cc
@bonewell 
@VladSemenyuk 
@DKlimenko 
@KKarlash 
@giangtqh
=> REVSDL-2505 Implement GPB nofitications

src/components/vr_module/include/vr_module/commands/activate_service.h, src/components/vr_module/src/commands/activate_service.cc, src/components/vr_module/test/src/activate_service_test.cc
- We don't have to send ActivateSupport to mobile side
=> Fix ActivateSupport command.

src/components/vr_cooperation/src/command_factory.cc
@KKarlash 
@thinhts 
@bonewell 
@VladSemenyuk 
@DKlimenko 
please review
=> Update CommandFactory to create Activate and Support Service request

src/components/vr_cooperation/include/vr_cooperation/command_factory.h, src/components/vr_cooperation/include/vr_cooperation/commands/base_gpb_request.h, src/components/vr_cooperation/include/vr_cooperation/commands/support_service_request.h, src/components/vr_cooperation/net/src/socket.cc, src/components/vr_cooperation/src/command/base_gpb_request.cc, src/components/vr_cooperation/src/command/support_service_request.cc, src/components/vr_cooperation/src/command_factory.cc, src/components/vr_cooperation/src/vr_module.cc
@bonewell 
@VladSemenyuk 
@DKlimenko 
@giangtqh 
@thinhts
=> Fixed Support Service request implemenatation. Fixed socket.

src/appMain/smartDeviceLink.ini, src/components/functional_module/include/functional_module/generic_module.h, src/components/functional_module/src/generic_module.cc, src/components/functional_module/src/plugin_manager.cc, src/components/vr_cooperation/include/vr_cooperation/vr_module.h, src/components/vr_cooperation/src/vr_module.cc
@bonewell 
@VladSemenyuk 
@DKlimenko 
@giangtqh 
@thinhts
=> Added methods Start/Stop into GenericModule

src/components/vr_cooperation/src/command/register_service_request.cc, src/components/vr_cooperation/src/vr_module.cc
Please review
@KKarlash 
@giangtqh
=> REVSDL-2554 Register service fix

src/components/vr_cooperation/include/vr_cooperation/service_module.h, src/components/vr_cooperation/include/vr_cooperation/vr_module.h, src/components/vr_cooperation/src/command/base_gpb_request.cc, src/components/vr_cooperation/src/command/support_service_request.cc, src/components/vr_cooperation/src/vr_module.cc
@bonewell 
@VladSemenyuk 
@DKlimenko 
@giangtqh 
@thinhts
=> Fixed support service issue

src/components/vr_cooperation/include/vr_cooperation/commands/activate_service_request.h, src/components/vr_cooperation/include/vr_cooperation/commands/base_json_request.h, src/components/vr_cooperation/include/vr_cooperation/vr_module.h, src/components/vr_cooperation/include/vr_cooperation/vr_module_event.h, src/components/vr_cooperation/src/command/activate_service_request.cc, src/components/vr_cooperation/src/command/base_json_request.cc, src/components/vr_cooperation/src/command/process_data_request.cc, src/components/vr_cooperation/src/vr_module.cc, src/components/vr_cooperation/src/vr_module_event.cc
@KKarlash 
@bonewell 
@thinhts 
@VladSemenyuk 
@DKlimenko 
please review
=> REVSDL-2571 Fix RSDL dump when receive ActivateRequest

src/components/vr_module/include/vr_module/commands/activate_service.h, src/components/vr_module/src/commands/activate_service.cc, src/components/vr_module/test/src/activate_service_test.cc
This reverts commit 8ec70443dc8b78954341001f86fb782942dc8c2b.
=> Revert "Fix ActivateSupport command."

src/components/vr_cooperation/include/vr_cooperation/commands/process_data_request.h, src/components/vr_cooperation/src/command/process_data_request.cc, src/components/vr_cooperation/src/command_factory.cc, src/components/vr_cooperation/src/vr_module.cc
Please review
@KKarlash 
@DKlimenko 
@VladSemenyuk 
@bonewell 
@giangtqh
=> REVSDL-2595 RSDL does not send request to mobile

src/components/vr_cooperation/src/command/on_default_service_chosen_notification.cc
Please review
@DKlimenko 
@bonewell 
@KKarlash 
@VladSemenyuk 
@giangtqh
=> REVSDL-2583 VR native is not selected to be default service

src/components/vr_cooperation/CMakeLists.txt, src/components/vr_cooperation/include/vr_cooperation/service_module.h, src/components/vr_cooperation/include/vr_cooperation/vr_module.h, src/components/vr_cooperation/interface/hmi.proto, src/components/vr_cooperation/src/command/on_unregister_service_notification.cc, src/components/vr_cooperation/src/command/register_service_request.cc, src/components/vr_cooperation/src/command_factory.cc, src/components/vr_cooperation/src/vr_module.cc, src/components/vr_cooperation/test/CMakeLists.txt, src/components/vr_cooperation/test/src/on_unregister_service_test.cc
Please review
@KKarlash 
@DKlimenko 
@bonewell 
@VladSemenyuk 
@giangtqh
=> REVSDL-2597 OnServiceUnregistered notification GPB implementation

src/components/can_cooperation/include/can_cooperation/validators/validator.h, src/components/can_cooperation/src/validators/validator.cc, src/components/can_cooperation/test/CMakeLists.txt, src/components/can_cooperation/test/src/validators/validator.cc, src/components/functional_module/CMakeLists.txt
=> Start refactoring enum validation
